CREATE TABLE Customers (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(100) NOT NULL,
    Surname VARCHAR(100) NOT NULL,
    E_mail VARCHAR(100) NOT NULL
);

CREATE TABLE Seats (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Order_number INTEGER NOT NULL,
    Place_number INTEGER NOT NULL
);

CREATE TABLE Plays (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(100) NOT NULL,
    Author VARCHAR(100) NOT NULL
);

CREATE TABLE Performances (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Name VARCHAR(100) NOT NULL,
    Date_and_time DATETIME NOT NULL,
    The_play INTEGER NOT NULL,
    Ticket_price DECIMAL(10, 2),
    FOREIGN KEY (The_play) REFERENCES Plays(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE Applications (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Representation_number INTEGER NOT NULL,
    Date_and_time_of_the_application DATETIME NOT NULL,
    Number_of_tickets INTEGER NOT NULL,
    FOREIGN KEY (Representation_number) REFERENCES Performances(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE Sales (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Application_number INTEGER NOT NULL,
    Place_number INTEGER NOT NULL,
    Buyer_id INTEGER NOT NULL,
    The_amount DECIMAL(10, 2),
    FOREIGN KEY (Application_number) REFERENCES Applications(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION,
    FOREIGN KEY (Place_number) REFERENCES Seats(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION,
    FOREIGN KEY (Buyer_id) REFERENCES Customers(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION
);